apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ports.name }}-headless-service
  namespace: foodgram
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: {{ .Values.service.ports.name }}