apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-statefulset
  namespace: foodgram
  labels:
{{ include "redis.labels" . | indent 4 }}
spec:
  serviceName: {{ .Values.service.ports.name }}-headless-service
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.name }}
    spec:
      containers:
        - name: {{ .Values.statefulset.name }}
          image: "{{ .Values.statefulset.image.name }}:{{ .Values.statefulset.image.tag }}"
          imagePullPolicy: {{ .Values.statefulset.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.ports.port }}
          volumeMounts:
            - name: {{ .Chart.Name }}-storage
              mountPath: {{ .Values.statefulset.pvc.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Chart.Name }}-storage
      spec:
        accessModes:
          - {{ .Values.statefulset.pvc.accessModes | quote }}
        resources:
          requests:
            storage: {{ .Values.statefulset.pvc.storage | quote }}