service:
  type: ClusterIP
  ports:
    port: 80

statefulset:
  replicas: 1
  image:
    name: tkshabalin/foodgram-frontend
    tag: latest
  imagePullPolicy: Always

volumeMounts:
  config:
    name: nginx-config-volume
    mountPath: /etc/nginx/conf.d/default.conf
    subPath: default.conf
    subName: nginx-config
  media:
    name: media-volume
    mountPath: /app/media
    subName: media-pvc
  static:
    name: backend-static
    mountPath: /backend_static
    subName: static-pvc
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 120m
    memory: 150Mi

