apiVersion: v1
kind: Service
metadata:
  name: vault-nodeport
  namespace: vault
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: vault  
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 30200  