namespace: foodgram
svcName: celery-worker-service

global:
  secrets:
    db: db-secrets
    rabbitmq: rabbitmq-secrets
    vault: vault-approle
    externalApis: external-apis
  config:
    db: db-config
    rabbitmq: rabbitmq-config
  images:
    api:
      name: tkshabalin/foodgram-back
      tag: latest
      pullPolicy: IfNotPresent

statefulset:
  replicas: 0

deployment:
  replicas: 1
  command: ["celery"]
  args: ["-A", "foodgram.celery", "worker", "--loglevel=info"]
  env:
    values: {}
    secrets: {}
    config: {}

volumeMounts:
  media:
    name: media-volume
    mountPath: /app/media
    claimName: media-pvc
  static:
    name: backend-static
    mountPath: /backend_static
    claimName: static-pvc