apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  DJANGO_SETTINGS_MODULE: "foodgram.settings"
  DB_HOST: "database"
  DB_PORT: "5432"