apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: foodgram
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.images.api.name }}:{{ .Values.global.images.api.tag }}"
          imagePullPolicy: {{ .Values.global.images.api.pullPolicy }}
          command: ["gunicorn"]
          args: ["--chdir", "/app", "--bind", "0.0.0.0:8000", "--workers", "2", "--timeout", "120", "foodgram.wsgi:application"]
          ports:
            - containerPort: {{ .Values.service.ports.port }}
          volumeMounts:
            - name: {{ .Values.volumeMounts.media.name }}
              mountPath: {{ .Values.volumeMounts.media.mountPath }}
            - name: {{ .Values.volumeMounts.static.name }}
              mountPath: {{ .Values.volumeMounts.static.mountPath }}
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "foodgram.settings"

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD

            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: host
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: port

            - name: NEWSAPI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-apis
                  key: NEWSAPI_API_KEY
            - name: NEWSDATA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: external-apis
                  key: NEWSDATA_API_KEY
          resources: {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: {{ .Values.volumeMounts.media.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeMounts.media.claimName }}
        - name: {{ .Values.volumeMounts.static.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeMounts.static.claimName }}