apiVersion: v1
kind: ConfigMap
metadata:
  namespace: foodgram
  name: db-config
  labels:
{{ include "db.labels" . | indent 4 }}
data:
  host: {{ .Values.service.ports.host | quote }}
  port: {{ .Values.service.ports.port | quote }}