apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.ports.host }}
  namespace: foodgram
  labels:
{{ include "db.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  sessionAffinity: None
  ports:
    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      protocol: {{ .Values.service.ports.protocol }}
  selector:
    app: {{ .Values.statefulset.app }}