apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-sts
  namespace: foodgram
  labels:
{{ include "db.labels" . | indent 4 }}
spec:
  serviceName: {{ .Values.service.ports.host | quote }}
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.app }}
    spec:
      containers:
        - name: {{ .Values.statefulset.app }}
          image: "{{ .Values.statefulset.image.name }}:{{ .Values.statefulset.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.ports.port }}
          envFrom:
            - secretRef:
                name: {{ include "db.secretsName" . }}
          volumeMounts:
            - name: {{ .Values.statefulset.name }}-storage
              mountPath: {{ .Values.statefulset.pvc.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.statefulset.name }}-storage
      spec:
        accessModes:
          - {{ .Values.statefulset.pvc.accessModes | quote }}
        resources:
          requests:
            storage: {{ .Values.statefulset.pvc.storage | quote }}