apiVersion: v1
kind: Secret
metadata:
  name: {{ include "db.secretsName" . }}
  namespace: foodgram
  labels:
{{ include "db.labels" . | indent 4 }}
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
