apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-job
  namespace: foodgram
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.global.images.api.name }}:{{ .Values.global.images.api.tag }}"
          imagePullPolicy: {{ .Values.global.images.api.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - "python /app/manage.py makemigrations users recipes api services && python /app/manage.py migrate"
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "foodgram.settings"

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD