namespace: foodgram
svcName: flower-service

global:
  namespace: foodgram
  name: flower
  svcName: flower-service
  environment: development
  secrets:
    db: db-secrets
    rabbitmq: rabbitmq-secrets
    vault: vault-approle
    externalApis: external-apis
  config:
    db: db-config
    rabbitmq: rabbitmq-config
  images:
    api:
      name: tkshabalin/foodgram-back
      tag: latest
      pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: foodgram.local
  tls:
    enabled: false
    secretName: foodgram-tls

service:
  type: ClusterIP
  ports:
    port: 5555
    targetPort: 5555

statefulset:
  replicas: 0

deployment:
  replicas: 1
  command: ["celery"]
  args: ["-A", "foodgram.celery", "flower", "--port=5555"]
  env:
    values: {}
    secrets: {}
    config: {}
  resources: {}

volumeMounts:
  media:
    name: media-volume
    mountPath: /app/media
    claimName: media-pvc
  static:
    name: backend-static
    mountPath: /backend_static
    claimName: static-pvc
