namespace: foodgram

image:
  name: tkshabalin/foodgram-back
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    port: 8000

deployment:
  replicas: 1
  command: ["gunicorn"]
  resources:
    requests:
      cpu: 200m
      memory: 130Mi
    limits:
      cpu: 370m
      memory: 138Mi

volumeMounts:
  media:
    name: media-volume
    mountPath: /app/media
    claimName: media-pvc
  static:
    name: backend-static
    mountPath: /backend_static
    claimName: static-pvc