apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  namespace: foodgram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: foodgram-back:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: media-volume
              mountPath: /app/media
            - name: backend-static
              mountPath: /backend_static
          env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: POSTGRES_PASSWORD
          - name: DB_HOST
            value: postgres
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
        - name: backend-static
          persistentVolumeClaim:
            claimName: static-pvc