apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: foodgram
  labels:
{{ include "nginx.labels" . | indent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;
    
        location / {
            try_files $uri /index.html;
        }
    
        location /media/ {
          alias /app/media/;
          expires 30d;
        }

        location /static/ {
            root /usr/share/nginx/html;
            expires 1y;
            add_header Cache-Control "public";
        }
    
        location /backend_static/ {
            alias /backend_static/;
            expires 1y;
            add_header Cache-Control "public";
        }
    
        location /api/ {
            proxy_pass http://back-service:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    
        location /admin/ {
          proxy_pass http://back-service:8000;
          proxy_set_header Host $host;
        }
    
        location /ws/ {
          proxy_pass http://back-service:8001;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
        }
    }