apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: foodgram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: foodgram-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: media-volume
            mountPath: /app/media
          - name: backend-static
            mountPath: /backend_static
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc
        - name: backend-static
          persistentVolumeClaim:
            claimName: static-pvc